command_handlers:
  - GOTO
  - MOVE
  - TURN
  - DOCK
  - RLC_GOTO
  - RLC_MOVE
  - RLC_TURN
  - RLC_CHARGE
  - RLC_UNCHARGE
#  - RLC_PICK
#  - RLC_PLACE
#  - RLC_GOTO_GPS
  - WAIT
#  - SET_BOOL
#  - CUSTOM_WAIT

# ACTIONS

GOTO:
  type: move_base_action_interface/MoveBaseActionInterface
  namespace: move_base
  frame_id: $(arg fixed_frame)

MOVE:
  type: move_action_interface/MoveActionInterface
  namespace: move

TURN:
  type: move_action_interface/TurnActionInterface
  namespace: move

DOCK:
  type: dock_action_interface/DockActionInterface
  namespace: pp_docker

WAIT:
  type: wait_action_interface/WaitActionInterface
  namespace: any

# SERVICES

ELEVATOR:
  type: elevator_service_interface/ElevatorServiceInterface
  namespace: robotnik_base_control/set_elevator

SET_BOOL:
  type: std_setbool_service_interface/StdSetBoolServiceInterface
  namespace: fake_capture/set_lights

# PROCEDURES

RLC_GOTO:
  type: goto_procedure_interface/GoToProcedureInterface
  namespace: GoToComponent
  frame_id: robot_map

RLC_MOVE:
  type: move_linear_procedure_interface/MoveLinearProcedureInterface
  namespace: MoveComponent

RLC_TURN:
  type: move_angular_procedure_interface/MoveAngularProcedureInterface
  namespace: MoveComponent

RLC_CHARGE:
  type: charge_procedure_interface/ChargeProcedureInterface
  namespace: ChargeComponent

RLC_UNCHARGE:
  type: uncharge_procedure_interface/UnchargeProcedureInterface
  namespace: UnchargeComponent

RLC_PICK:
  type: pick_procedure_interface/PickProcedureInterface
  namespace: PickComponent

RLC_PLACE:
  type: place_procedure_interface/PlaceProcedureInterface
  namespace: PlaceComponent

RLC_GOTO_GPS:
  type: goto_gps_procedure_interface/GoToGPSProcedureInterface
  namespace: GoToGPSComponent


## HANDLER FROM CUSTOM PACKAGE
CUSTOM_WAIT:
  type: my_custom_commands_handlers/wait_action_interface/WaitActionInterface
  namespace: any
