sequences:
  GOTO_TEST:
    - GOTO 1 0 0
    - GOTO 1 2 0
    - GOTO -1 0 0
  GOTO_TEST2:
    - GOTO 3 0 0
    - GOTO -3 0 0
    - GOTO 2 2 3.14
  DEMO_RB1_SIM:
    - RLC_GOTO -1.42 -1.79 -1.5181
    - RLC_PICK robot_cart_laser
    - RLC_GOTO 3.53 -2.24 -1.50
    - RLC_GOTO 3.51 -3.30 -1.58
    - RLC_PLACE
    - RLC_GOTO 0.94 2.63 1.53
    - RLC_CHARGE
