#!/bin/bash
sudo dpkg -i ros-melodic-costmap-prohibition-layer_0.0.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-icp-pose-corrector_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-image-filter_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-multimap-server-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-multimap-server_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-network-monitor_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures-msgs_1.0.3-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures-test-msgs_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rbkairos-5-plus-config_0.3.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rbkairos-plus-ur5-vgc10-moveit-config_0.3.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-bringup_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-bringup_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-test_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-simple-command-manager-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-simple-command-sequencer_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-msgs_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-marker-mapping_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rcomponent_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-battery-estimation_1.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-charge-manager_1.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-daly-bms_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-simple-command-manager_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-base-hw-lib_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-navigation-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-docker_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-locator_1.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-move_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-pad-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-pose-filter_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-safety-controller_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-signal-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-msgs_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-velocity-limiter_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon-msgs_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon-core_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rqt-rosmon_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-safety-module_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-service-shifter_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-procedures_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-components_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-dummy-components_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-summit-xl-j2s6s200-moveit-config_0.3.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-summit-xl-j2s6s300-moveit-config_0.3.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-universal-robot_1.2.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-ur-bringup_1.2.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-ur-driver_1.2.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-ur-e-description_1.2.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-ur-e-gazebo_1.2.5-0bionic_amd64.deb
sudo dpkg -i ros-melodic-ur-msgs_1.2.5-0bionic_amd64.deb
