#!/bin/bash
sudo apt-get remove -y ros-melodic-ur-msgs 
sudo apt-get remove -y ros-melodic-ur-e-gazebo 
sudo apt-get remove -y ros-melodic-ur-e-description 
sudo apt-get remove -y ros-melodic-ur-driver 
sudo apt-get remove -y ros-melodic-ur-bringup 
sudo apt-get remove -y ros-melodic-universal-robot 
sudo apt-get remove -y ros-melodic-summit-xl-j2s6s300-moveit-config 
sudo apt-get remove -y ros-melodic-summit-xl-j2s6s200-moveit-config 
sudo apt-get remove -y ros-melodic-robot-local-control-dummy-components 
sudo apt-get remove -y ros-melodic-robot-local-control-components 
sudo apt-get remove -y ros-melodic-robot-local-control 
sudo apt-get remove -y ros-melodic-robot-local-control-procedures 
sudo apt-get remove -y ros-melodic-procedures 
sudo apt-get remove -y ros-melodic-service-shifter 
sudo apt-get remove -y ros-melodic-safety-module 
sudo apt-get remove -y ros-melodic-rosmon 
sudo apt-get remove -y ros-melodic-rqt-rosmon 
sudo apt-get remove -y ros-melodic-rosmon-core 
sudo apt-get remove -y ros-melodic-rosmon-msgs 
sudo apt-get remove -y ros-melodic-robotnik-velocity-limiter 
sudo apt-get remove -y ros-melodic-robot-local-control-msgs 
sudo apt-get remove -y ros-melodic-robotnik-signal-msgs 
sudo apt-get remove -y ros-melodic-robotnik-safety-controller 
sudo apt-get remove -y ros-melodic-robotnik-pose-filter 
sudo apt-get remove -y ros-melodic-robotnik-pad-msgs 
sudo apt-get remove -y ros-melodic-robotnik-move 
sudo apt-get remove -y ros-melodic-robotnik-locator 
sudo apt-get remove -y ros-melodic-robotnik-docker 
sudo apt-get remove -y ros-melodic-robotnik-navigation-msgs 
sudo apt-get remove -y ros-melodic-robotnik-base-hw-lib 
sudo apt-get remove -y ros-melodic-robot-simple-command-manager 
sudo apt-get remove -y ros-melodic-daly-bms 
sudo apt-get remove -y ros-melodic-charge-manager 
sudo apt-get remove -y ros-melodic-battery-estimation 
sudo apt-get remove -y ros-melodic-rcomponent 
sudo apt-get remove -y ros-melodic-marker-mapping 
sudo apt-get remove -y ros-melodic-robotnik-msgs 
sudo apt-get remove -y ros-melodic-robot-simple-command-sequencer 
sudo apt-get remove -y ros-melodic-robot-simple-command-manager-msgs 
sudo apt-get remove -y ros-melodic-robot-local-control-test 
sudo apt-get remove -y ros-melodic-robot-local-control-bringup 
sudo apt-get remove -y ros-melodic-robot-bringup 
sudo apt-get remove -y ros-melodic-rbkairos-plus-ur5-vgc10-moveit-config 
sudo apt-get remove -y ros-melodic-rbkairos-5-plus-config 
sudo apt-get remove -y ros-melodic-procedures-test-msgs 
sudo apt-get remove -y ros-melodic-procedures-msgs 
sudo apt-get remove -y ros-melodic-network-monitor 
sudo apt-get remove -y ros-melodic-multimap-server 
sudo apt-get remove -y ros-melodic-multimap-server-msgs 
sudo apt-get remove -y ros-melodic-image-filter 
sudo apt-get remove -y ros-melodic-icp-pose-corrector 
sudo apt-get remove -y ros-melodic-costmap-prohibition-layer 
